In [1]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/train.csv')
df

id keyword location  \
0         1     NaN      NaN   
1         4     NaN      NaN   
2         5     NaN      NaN   
3         6     NaN      NaN   
4         7     NaN      NaN   
...     ...     ...      ...   
7608  10869     NaN      NaN   
7609  10870     NaN      NaN   
7610  10871     NaN      NaN   
7611  10872     NaN      NaN   
7612  10873     NaN      NaN   

                                                   text  target  
0     Our Deeds are the Reason of this #earthquake M...       1  
1                Forest fire near La Ronge Sask. Canada       1  
2     All residents asked to 'shelter in place' are ...       1  
3     13,000 people receive #wildfires evacuation or...       1  
4     Just got sent this photo from Ruby #Alaska as ...       1  
...                                                 ...     ...  
7608  Two giant cranes holding a bridge collapse int...       1  
7609  @aria_ahrary @TheTawniest The out of control w...       1  
7610  M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...       1  
7611  Police investigating after an e-bike collided ...       1  
7612  The Latest: More Homes Razed by Northern Calif...       1  

[7613 rows x 5 columns]

Feature Enginering

In [2]:
import urllib.parse
# Replace NaN with an empty string
df['keyword'] = df['keyword'].fillna('')

# Apply unquote to each element in the 'keyword' column
df['keyword'] = df['keyword'].apply(urllib.parse.unquote)


In [3]:
import re
# Replace NaN with an empty string
df['location'] = df['location'].fillna('')

# Apply unquote to each element in the 'location' column
df['location'] = df['location'].apply(urllib.parse.unquote)

# Filter out rows with location consisting solely of non-alphanumeric characters
df['location'] = df['location'].apply(lambda x: x if re.search(r'\w', x) else '')

print(df['location'])

0        
1        
2        
3        
4        
       ..
7608     
7609     
7610     
7611     
7612     
Name: location, Length: 7613, dtype: object


In [4]:
df['location'].shape

(7613,)

In [5]:
# Apply unquote to each element in the 'location' column
df['location'] = df['location'].apply(urllib.parse.unquote)

# Filter out rows with location consisting solely of non-alphanumeric characters or non-English words
# Replace locations consisting solely of non-alphanumeric characters or non-English words with 'Invalid Location'
df['location'] = df['location'].apply(lambda x: x if re.match(r'^[A-Za-z\s]*$', x) else '')


print(df['location'])

0        
1        
2        
3        
4        
       ..
7608     
7609     
7610     
7611     
7612     
Name: location, Length: 7613, dtype: object


In [ ]:
for x in df['location']:
  print(x)

Streaming output truncated to the last 5000 lines.
Valle Del Sol

New York NYC



Moscow






Maldives






Yooooooo
New York City

Jersey

London




denver colorado



Paname City








Colorado


Brasil
Worldwide




In My Lab Creating 


Bikini bottom




Worldwide
Northern Ireland






















New York


Bangkok Thailand

New York


New York


New York
Geneva


Manchester

Manchester


REPUBLICA DOMINICANA


FOLLOWS YOU everywhere you go
Birmingham

London


Indonesia

The Meadow
Bournemouth



Chester 


Banbridge


probably petting an animal


Varies 
ACCRA GHANA
Columbus

St Joseph de Beauce


uk
Seattle
  News




United States







Vancouver BC

Brasil
ITALY



EVERYWHERE
Washington DC



Washington DC


Jackson TN





chillin at ceder rapids


en el pais de los arrechos

Nigeria

San Francisco




Naperville


In Your Notifications 




London
los angeles


nearest trash can 
USA 
Atlanta


Morocco
Pedophile hunting ground



Asia Pacific   
North Carolina




In [6]:
import re
# Replace NaN with an empty string
df['text'] = df['text'].fillna('')

# Apply unquote to each element in the 'location' column
df['text'] = df['text'].apply(urllib.parse.unquote)

# Filter out rows with location consisting solely of non-alphanumeric characters
df['text'] = df['text'].apply(lambda x: x if re.search(r'\w', x) else '')

print(df['text'])

0       Our Deeds are the Reason of this #earthquake M...
1                  Forest fire near La Ronge Sask. Canada
2       All residents asked to 'shelter in place' are ...
3       13,000 people receive #wildfires evacuation or...
4       Just got sent this photo from Ruby #Alaska as ...
                              ...                        
7608    Two giant cranes holding a bridge collapse int...
7609    @aria_ahrary @TheTawniest The out of control w...
7610    M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...
7611    Police investigating after an e-bike collided ...
7612    The Latest: More Homes Razed by Northern Calif...
Name: text, Length: 7613, dtype: object


In [7]:
# Apply unquote to each element in the 'location' column
df['text'] = df['text'].apply(urllib.parse.unquote)

# Filter out rows with location consisting solely of non-alphanumeric characters or non-English words
df['text'] = df['text'].apply(lambda x: x if re.match(r'^[A-Za-z\s]*$', x) else '')

print(df['text'])

0        
1        
2        
3        
4        
       ..
7608     
7609     
7610     
7611     
7612     
Name: text, Length: 7613, dtype: object


In [ ]:
df

id keyword location text  target
0         1                             1
1         4                             1
2         5                             1
3         6                             1
4         7                             1
...     ...     ...      ...  ...     ...
7608  10869                             1
7609  10870                             1
7610  10871                             1
7611  10872                             1
7612  10873                             1

[7613 rows x 5 columns]

In [ ]:
df.to_csv('/content/drive/MyDrive/clean_data.csv', index=False)

In [8]:
df['keyword']= df['keyword'].str.lower()
df['location']= df['location'].str.lower()
df['text']= df['text'].str.lower()
df

id keyword location text  target
0         1                             1
1         4                             1
2         5                             1
3         6                             1
4         7                             1
...     ...     ...      ...  ...     ...
7608  10869                             1
7609  10870                             1
7610  10871                             1
7611  10872                             1
7612  10873                             1

[7613 rows x 5 columns]

In [9]:
# Concatenate 'keywords', 'location', and 'text' into a new column 'text_cleaned'
df['text_cleaned'] = df['keyword'] + ' ' + df['location'] + ' ' + df['text']

# Print the new DataFrame with the 'text_cleaned' column
print(df[['text_cleaned']])

     text_cleaned
0                
1                
2                
3                
4                
...           ...
7608             
7609             
7610             
7611             
7612             

[7613 rows x 1 columns]


In [ ]:
df['text_cleaned'].shape

(7613,)

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk import download

# Download necessary NLTK data files
download('punkt')
download('stopwords')

# Initialize the Porter Stemmer
stemmer = PorterStemmer()

# Initialize the stopwords set
stop_words = set(stopwords.words('english'))

# Function to perform lemmatization and stemming
def preprocess_text(text):
    # Tokenize the text
    tokens = word_tokenize(text)
    # Perform stemming
    stemmed_tokens = [stemmer.stem(word) for word in tokens if word.isalpha() and word not in stop_words]
    # Join tokens back into a string
    return ' '.join(stemmed_tokens)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
print(df['target'].value_counts())

target
0    4342
1    3271
Name: count, dtype: int64


In [11]:
# Apply preprocessing to the 'text_cleaned' column (lemmatization + stemming)
df['text_cleaned'] = df['text_cleaned'].apply(preprocess_text)

# Initialize the TF-IDF Vectorizer
vectorizer = TfidfVectorizer(stop_words='english')  # `stop_words='english'` removes common English words

# Fit and transform the 'text_cleaned' column
tfidf_matrix = vectorizer.fit_transform(df['text_cleaned'])

# Convert the TF-IDF matrix to a DataFrame
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=vectorizer.get_feature_names_out())

# Print the TF-IDF DataFrame
print("TF-IDF Matrix:")
print(tfidf_df)

# Print the feature names
print("\nFeature Names:")
print(vectorizer.get_feature_names_out())

TF-IDF Matrix:
      aan  aberdeenshir  ablaz  absolut  abuja  accept  accid  account  accra  \
0     0.0           0.0    0.0      0.0    0.0     0.0    0.0      0.0    0.0   
1     0.0           0.0    0.0      0.0    0.0     0.0    0.0      0.0    0.0   
2     0.0           0.0    0.0      0.0    0.0     0.0    0.0      0.0    0.0   
3     0.0           0.0    0.0      0.0    0.0     0.0    0.0      0.0    0.0   
4     0.0           0.0    0.0      0.0    0.0     0.0    0.0      0.0    0.0   
...   ...           ...    ...      ...    ...     ...    ...      ...    ...   
7608  0.0           0.0    0.0      0.0    0.0     0.0    0.0      0.0    0.0   
7609  0.0           0.0    0.0      0.0    0.0     0.0    0.0      0.0    0.0   
7610  0.0           0.0    0.0      0.0    0.0     0.0    0.0      0.0    0.0   
7611  0.0           0.0    0.0      0.0    0.0     0.0    0.0      0.0    0.0   
7612  0.0           0.0    0.0      0.0    0.0     0.0    0.0      0.0    0.0   

      act  .

Training with few Machine Learning models

In [12]:
x= tfidf_df
y= df['target']

In [ ]:
from sklearn.model_selection import train_test_split
# Perform the train-test split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(6090, 2162)
(1523, 2162)
(6090,)
(1523,)


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Initialize the Logistic Regression model
model = LogisticRegression()

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

# Print evaluation metrics
print(f'Accuracy: {accuracy}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)

Accuracy: 0.7058437294812869
Confusion Matrix:
[[685 189]
 [259 390]]
Classification Report:
              precision    recall  f1-score   support

           0       0.73      0.78      0.75       874
           1       0.67      0.60      0.64       649

    accuracy                           0.71      1523
   macro avg       0.70      0.69      0.69      1523
weighted avg       0.70      0.71      0.70      1523



In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt
from sklearn import tree

# Initialize the Decision Tree model
model = DecisionTreeClassifier()

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

# Print evaluation metrics
print(f'Accuracy: {accuracy}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)


Accuracy: 0.6887721602101117
Confusion Matrix:
[[642 232]
 [242 407]]
Classification Report:
              precision    recall  f1-score   support

           0       0.73      0.73      0.73       874
           1       0.64      0.63      0.63       649

    accuracy                           0.69      1523
   macro avg       0.68      0.68      0.68      1523
weighted avg       0.69      0.69      0.69      1523



In [ ]:
from sklearn.neighbors import KNeighborsClassifier
# Initialize the KNN model
# You can change the 'n_neighbors' parameter based on your needs
model = KNeighborsClassifier(n_neighbors=3)

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

# Print evaluation metrics
print(f'Accuracy: {accuracy}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)

Accuracy: 0.6565988181221274
Confusion Matrix:
[[668 206]
 [317 332]]
Classification Report:
              precision    recall  f1-score   support

           0       0.68      0.76      0.72       874
           1       0.62      0.51      0.56       649

    accuracy                           0.66      1523
   macro avg       0.65      0.64      0.64      1523
weighted avg       0.65      0.66      0.65      1523



In [ ]:
from sklearn.svm import SVC

model = SVC(C=1.0, kernel='linear', gamma='scale', random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

# Print evaluation metrics
print(f'Accuracy: {accuracy}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)

Accuracy: 0.6986211424819435
Confusion Matrix:
[[672 202]
 [257 392]]
Classification Report:
              precision    recall  f1-score   support

           0       0.72      0.77      0.75       874
           1       0.66      0.60      0.63       649

    accuracy                           0.70      1523
   macro avg       0.69      0.69      0.69      1523
weighted avg       0.70      0.70      0.70      1523



In [ ]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, max_depth=None, random_state=42, n_jobs=-1)

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

# Print evaluation metrics
print(f'Accuracy: {accuracy}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)



Accuracy: 0.701247537754432
Confusion Matrix:
[[672 202]
 [253 396]]
Classification Report:
              precision    recall  f1-score   support

           0       0.73      0.77      0.75       874
           1       0.66      0.61      0.64       649

    accuracy                           0.70      1523
   macro avg       0.69      0.69      0.69      1523
weighted avg       0.70      0.70      0.70      1523



In [ ]:
X_train.shape

(6090, 2162)

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization

# Define the model
model = Sequential([
    Dense(256, activation='relu', input_shape=(X_train.shape[1],)),  # Correct input shape
    BatchNormalization(),
    Dropout(0.5),
    Dense(128, activation='relu'),
    BatchNormalization(),
    Dropout(0.5),
    Dense(64, activation='relu'),
    BatchNormalization(),
    Dropout(0.5),
    Dense(1, activation='sigmoid')
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train, epochs=20, batch_size=32, validation_split=0.2)

# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Accuracy: {accuracy}')

Epoch 1/20
153/153 [==============================] - 6s 14ms/step - loss: 0.8418 - accuracy: 0.5511 - val_loss: 0.7200 - val_accuracy: 0.4384
Epoch 2/20
153/153 [==============================] - 2s 12ms/step - loss: 0.6894 - accuracy: 0.6293 - val_loss: 0.6883 - val_accuracy: 0.4622
Epoch 3/20
153/153 [==============================] - 2s 12ms/step - loss: 0.6151 - accuracy: 0.6866 - val_loss: 0.6288 - val_accuracy: 0.6708
Epoch 4/20
153/153 [==============================] - 2s 12ms/step - loss: 0.5693 - accuracy: 0.7145 - val_loss: 0.5856 - val_accuracy: 0.7044
Epoch 5/20
153/153 [==============================] - 3s 17ms/step - loss: 0.5347 - accuracy: 0.7467 - val_loss: 0.5848 - val_accuracy: 0.7110
Epoch 6/20
153/153 [==============================] - 3s 18ms/step - loss: 0.5161 - accuracy: 0.7477 - val_loss: 0.5888 - val_accuracy: 0.6921
Epoch 7/20
153/153 [==============================] - 2s 11ms/step - loss: 0.5003 - accuracy: 0.7631 - val_loss: 0.5936 - val_accuracy: 0.6921

In [ ]:
from sklearn.ensemble import VotingClassifier

# Define individual models
model1 = MLPClassifier(hidden_layer_sizes=(128, 64), activation='relu', solver='adam', alpha=0.001, max_iter=1000)
model2 = MLPClassifier(hidden_layer_sizes=(64, 64), activation='tanh', solver='sgd', alpha=0.01, max_iter=1000)

# Define the voting classifier
voting_clf = VotingClassifier(estimators=[('mlp1', model1), ('mlp2', model2)], voting='soft')

# Fit the voting classifier
voting_clf.fit(X_train, y_train)

# Evaluate the voting classifier
y_pred = voting_clf.predict(X_test)
print(f'Accuracy: {accuracy_score(y_test, y_pred)}')
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))
print('Classification Report:')
print(classification_report(y_test, y_pred))


Accuracy: 0.6966513460275772
Confusion Matrix:
[[653 221]
 [241 408]]
Classification Report:
              precision    recall  f1-score   support

           0       0.73      0.75      0.74       874
           1       0.65      0.63      0.64       649

    accuracy                           0.70      1523
   macro avg       0.69      0.69      0.69      1523
weighted avg       0.70      0.70      0.70      1523



Training with custom trained word emmbeging model

In [13]:
!pip install gensim


In [16]:
import pandas as pd
from nltk.tokenize import word_tokenize

# Assuming df is your DataFrame
df['tokens'] = df['text_cleaned'].apply(word_tokenize)



In [20]:
for x in df['tokens']:
  print(x)

Streaming output truncated to the last 5000 lines.
['destruct', 'around', 'world']
['destruct']
['destruct', 'vall', 'del', 'sol']
['destruct']
['destruct', 'new', 'york', 'nyc']
['destruct']
['destruct']
['destruct']
['destruct', 'moscow']
['destruct']
['destruct']
['destruct']
['destruct']
['destruct']
['destruct']
['destruct', 'maldiv']
['destruct']
['destruct']
['destruct']
['destruct']
['destruct']
['destruct']
['destruct', 'yooooooo']
['destruct', 'new', 'york', 'citi']
['destruct']
['destruct', 'jersey']
['destruct']
['destruct', 'london']
['destruct']
['destruct', 'temptat', 'alway', 'lead', 'destruct']
['destruct']
['destruct']
['destruct', 'denver', 'colorado']
['deton']
['deton']
['deton']
['deton', 'panam', 'citi']
['deton']
['deton']
['deton']
['deton']
['deton']
['deton']
['deton']
['deton']
['deton', 'colorado']
['deton']
['deton']
['deton', 'brasil']
['deton', 'worldwid']
['deton']
['deton']
['deton']
['deton']
['deton', 'lab', 'creat']
['deton']
['deton']
['deton', 'bi

In [21]:
# Remove rows where 'tokens' is an empty list
df = df[df['tokens'].apply(len) > 0]

# Display the resulting DataFrame
print(df)

         id  keyword location  \
10       16                     
16       24                     
17       25                     
18       26                     
22       33                     
...     ...      ...      ...   
7580  10832  wrecked  london    
7581  10833  wrecked  lincoln   
7582  10834  wrecked            
7589  10843                     
7593  10848                     

                                                   text  target  \
10          three people died from the heat wave so far       1   
16                                        i love fruits       0   
17                                     summer is lovely       0   
18                                    my car is so fast       0   
22                                          love skiing       0   
...                                                 ...     ...   
7580                                                          0   
7581                                                          0   


In [22]:
for x in df['tokens']:
  print(x)

Streaming output truncated to the last 5000 lines.
['destroy', 'emot', 'destroy']
['destroy']
['destroy', 'bueno', 'air', 'argentina']
['destroy']
['destroy']
['destroy', 'usa']
['destroy', 'usa']
['destroy']
['destroy', 'usa']
['destroy']
['destroy', 'montreal']
['destroy']
['destroy']
['destroy']
['destroy']
['destroy']
['destroy']
['destroy', 'studio']
['destroy']
['destroy', 'usa']
['destroy', 'queen', 'new', 'york']
['destroy']
['destroy', 'usa']
['destroy']
['destroy']
['destroy']
['destroy', 'usa']
['destruct']
['destruct', 'around', 'world']
['destruct']
['destruct', 'vall', 'del', 'sol']
['destruct']
['destruct', 'new', 'york', 'nyc']
['destruct']
['destruct']
['destruct']
['destruct', 'moscow']
['destruct']
['destruct']
['destruct']
['destruct']
['destruct']
['destruct']
['destruct', 'maldiv']
['destruct']
['destruct']
['destruct']
['destruct']
['destruct']
['destruct']
['destruct', 'yooooooo']
['destruct', 'new', 'york', 'citi']
['destruct']
['destruct', 'jersey']
['destruct

In [23]:
from gensim.models import Word2Vec

# Prepare the tokenized data
tokenized_data = df['tokens'].tolist()

# Train the Word2Vec model
word2vec_model = Word2Vec(sentences=tokenized_data, vector_size=300, window=5, min_count=1, workers=4)


In [25]:
import numpy as np

def get_word2vec_embeddings(tokens, model):
    embeddings = [model.wv[word] for word in tokens if word in model.wv]
    if embeddings:
        return np.mean(embeddings, axis=0)
    else:
        return np.zeros(model.vector_size)

# Use .loc to set the values
df.loc[:, 'embeddings'] = df['tokens'].apply(lambda x: get_word2vec_embeddings(x, word2vec_model))

# Display the resulting DataFrame
print(df)



         id  keyword location  \
10       16                     
16       24                     
17       25                     
18       26                     
22       33                     
...     ...      ...      ...   
7580  10832  wrecked  london    
7581  10833  wrecked  lincoln   
7582  10834  wrecked            
7589  10843                     
7593  10848                     

                                                   text  target  \
10          three people died from the heat wave so far       1   
16                                        i love fruits       0   
17                                     summer is lovely       0   
18                                    my car is so fast       0   
22                                          love skiing       0   
...                                                 ...     ...   
7580                                                          0   
7581                                                          0   


In [28]:
df

id  keyword location  \
10       16                     
16       24                     
17       25                     
18       26                     
22       33                     
...     ...      ...      ...   
7580  10832  wrecked  london    
7581  10833  wrecked  lincoln   
7582  10834  wrecked            
7589  10843                     
7593  10848                     

                                                   text  target  \
10          three people died from the heat wave so far       1   
16                                        i love fruits       0   
17                                     summer is lovely       0   
18                                    my car is so fast       0   
22                                          love skiing       0   
...                                                 ...     ...   
7580                                                          0   
7581                                                          0   
7582                                                          0   
7589                                     omg earthquake       1   
7593  i just heard a really loud bang and everyone i...       0   

                                     text_cleaned  \
10                  three peopl die heat wave far   
16                                     love fruit   
17                                    summer love   
18                                       car fast   
22                                       love ski   
...                                           ...   
7580                                 wreck london   
7581                                wreck lincoln   
7582                                        wreck   
7589                                omg earthquak   
7593  heard realli loud bang everyon asleep great   

                                                 tokens  \
10                 [three, peopl, die, heat, wave, far]   
16                                        [love, fruit]   
17                                       [summer, love]   
18                                          [car, fast]   
22                                          [love, ski]   
...                                                 ...   
7580                                    [wreck, london]   
7581                                   [wreck, lincoln]   
7582                                            [wreck]   
7589                                   [omg, earthquak]   
7593  [heard, realli, loud, bang, everyon, asleep, g...   

                                             embeddings  
10    [0.0018437585, 0.00073071494, -0.0028032332, 0...  
16    [0.0007594274, -0.0011230662, -0.0024172552, -...  
17    [0.0023167883, 0.00053406507, -0.00012989412, ...  
18    [-0.00044936477, 0.0009967581, 0.0018735949, 0...  
22    [0.00017912884, 0.0003779557, -0.0024340816, 0...  
...                                                 ...  
7580  [-0.00048519898, 0.0014995437, -0.0014497312, ...  
7581  [3.1172764e-05, 0.0017924428, -0.00030324934, ...  
7582  [-0.0025675958, 0.003581372, -0.0021472012, 8....  
7589  [0.00035094787, 0.0005972614, 0.00067346107, -...  
7593  [0.0027503506, 0.0022410122, -0.0022945644, 0....  

[7561 rows x 8 columns]

In [42]:
# Convert embeddings to a numpy array
X = np.array(df['embeddings'].tolist())
y = df['target'].values


In [43]:
from sklearn.model_selection import train_test_split
# Perform the train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [45]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(6048, 300)
(1513, 300)
(6048,)
(1513,)


In [44]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Initialize the Logistic Regression model
model = LogisticRegression()

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

# Print evaluation metrics
print(f'Accuracy: {accuracy}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)

Accuracy: 0.5789821546596167
Confusion Matrix:
[[876   0]
 [637   0]]
Classification Report:
              precision    recall  f1-score   support

           0       0.58      1.00      0.73       876
           1       0.00      0.00      0.00       637

    accuracy                           0.58      1513
   macro avg       0.29      0.50      0.37      1513
weighted avg       0.34      0.58      0.42      1513



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [47]:
from sklearn.ensemble import VotingClassifier
from sklearn.neural_network import MLPClassifier
# Define individual models
model1 = MLPClassifier(hidden_layer_sizes=(128, 64), activation='relu', solver='adam', alpha=0.001, max_iter=1000)
model2 = MLPClassifier(hidden_layer_sizes=(64, 64), activation='tanh', solver='sgd', alpha=0.01, max_iter=1000)

# Define the voting classifier
voting_clf = VotingClassifier(estimators=[('mlp1', model1), ('mlp2', model2)], voting='soft')

# Fit the voting classifier
voting_clf.fit(X_train, y_train)

# Evaluate the voting classifier
y_pred = voting_clf.predict(X_test)
print(f'Accuracy: {accuracy_score(y_test, y_pred)}')
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))
print('Classification Report:')
print(classification_report(y_test, y_pred))

Accuracy: 0.712491738268341
Confusion Matrix:
[[760 116]
 [319 318]]
Classification Report:
              precision    recall  f1-score   support

           0       0.70      0.87      0.78       876
           1       0.73      0.50      0.59       637

    accuracy                           0.71      1513
   macro avg       0.72      0.68      0.69      1513
weighted avg       0.72      0.71      0.70      1513



In [48]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization

# Define the model
model = Sequential([
    Dense(256, activation='relu', input_shape=(X_train.shape[1],)),  # Correct input shape
    BatchNormalization(),
    Dropout(0.5),
    Dense(128, activation='relu'),
    BatchNormalization(),
    Dropout(0.5),
    Dense(64, activation='relu'),
    BatchNormalization(),
    Dropout(0.5),
    Dense(1, activation='sigmoid')
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train, epochs=20, batch_size=32, validation_split=0.2)

# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Accuracy: {accuracy}')

Epoch 1/20
152/152 [==============================] - 6s 15ms/step - loss: 0.9197 - accuracy: 0.5415 - val_loss: 0.7098 - val_accuracy: 0.5570
Epoch 2/20
152/152 [==============================] - 1s 8ms/step - loss: 0.7712 - accuracy: 0.5850 - val_loss: 0.7093 - val_accuracy: 0.5570
Epoch 3/20
152/152 [==============================] - 1s 9ms/step - loss: 0.7075 - accuracy: 0.6131 - val_loss: 0.6748 - val_accuracy: 0.5554
Epoch 4/20
152/152 [==============================] - 1s 8ms/step - loss: 0.6757 - accuracy: 0.6273 - val_loss: 0.6324 - val_accuracy: 0.6248
Epoch 5/20
152/152 [==============================] - 1s 6ms/step - loss: 0.6351 - accuracy: 0.6558 - val_loss: 0.6008 - val_accuracy: 0.6711
Epoch 6/20
152/152 [==============================] - 1s 5ms/step - loss: 0.6194 - accuracy: 0.6683 - val_loss: 0.5910 - val_accuracy: 0.6884
Epoch 7/20
152/152 [==============================] - 1s 6ms/step - loss: 0.6052 - accuracy: 0.6759 - val_loss: 0.5882 - val_accuracy: 0.6967
Epoch

Pretrained word embedding models


In [51]:
import gensim.downloader as api

# Load the lightweight pre-trained GloVe model
glove_model = api.load('glove-wiki-gigaword-50')


[==================================================] 100.0% 66.0/66.0MB downloaded


In [52]:
# Tokenize the text data
df['tokens'] = df['text_cleaned'].apply(word_tokenize)

# Remove rows where 'tokens' is an empty list
df = df[df['tokens'].apply(len) > 0].copy()

<ipython-input-52-6d298c811af4>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tokens'] = df['text_cleaned'].apply(word_tokenize)


In [53]:
import numpy as np

def get_glove_embeddings(tokens, model):
    embeddings = [model[word] for word in tokens if word in model]
    if embeddings:
        return np.mean(embeddings, axis=0)
    else:
        return np.zeros(model.vector_size)

# Use .loc to set the values
df.loc[:, 'embeddings'] = df['tokens'].apply(lambda x: get_glove_embeddings(x, glove_model))

# Ensure embeddings are numpy arrays
df['embeddings'] = df['embeddings'].apply(lambda x: x.tolist())


In [54]:
df['embeddings']

10      [0.2979840040206909, 0.13876000046730042, 0.57...
16      [0.228410005569458, 0.6823750138282776, -0.991...
17      [-0.13940000534057617, 1.1020500659942627, -0....
18      [0.1345050036907196, -0.4447009861469269, 0.78...
22      [-0.24433499574661255, 1.3529000282287598, -0....
                              ...                        
7580    [0.40821802616119385, 0.6297950148582458, -0.0...
7581    [0.6495649814605713, 0.6671600341796875, 0.434...
7582    [0.7835500240325928, 0.26322001218795776, 0.65...
7589    [0.061769999563694, -0.27821001410484314, 0.17...
7593    [-0.0007974065956659615, -0.14809198677539825,...
Name: embeddings, Length: 7561, dtype: object

In [56]:
# Convert embeddings to a numpy array
X = np.array(df['embeddings'].tolist())
y = df['target'].values

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [57]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the classifier
clf.fit(X_train, y_train)

# Make predictions
y_pred = clf.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

# Print other evaluation metrics
print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.67
Classification Report:
              precision    recall  f1-score   support

           0       0.67      0.85      0.75       876
           1       0.67      0.42      0.52       637

    accuracy                           0.67      1513
   macro avg       0.67      0.63      0.63      1513
weighted avg       0.67      0.67      0.65      1513

Confusion Matrix:
[[741 135]
 [369 268]]


In [58]:
from sklearn.ensemble import VotingClassifier
from sklearn.neural_network import MLPClassifier
# Define individual models
model1 = MLPClassifier(hidden_layer_sizes=(128, 64), activation='relu', solver='adam', alpha=0.001, max_iter=1000)
model2 = MLPClassifier(hidden_layer_sizes=(64, 64), activation='tanh', solver='sgd', alpha=0.01, max_iter=1000)

# Define the voting classifier
voting_clf = VotingClassifier(estimators=[('mlp1', model1), ('mlp2', model2)], voting='soft')

# Fit the voting classifier
voting_clf.fit(X_train, y_train)

# Evaluate the voting classifier
y_pred = voting_clf.predict(X_test)
print(f'Accuracy: {accuracy_score(y_test, y_pred)}')
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))
print('Classification Report:')
print(classification_report(y_test, y_pred))

Accuracy: 0.6649041639127561
Confusion Matrix:
[[704 172]
 [335 302]]
Classification Report:
              precision    recall  f1-score   support

           0       0.68      0.80      0.74       876
           1       0.64      0.47      0.54       637

    accuracy                           0.66      1513
   macro avg       0.66      0.64      0.64      1513
weighted avg       0.66      0.66      0.65      1513

